version: '3'
services:
  db:
    image: postgres
    container_name: postgres1
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "mydb"
    network_mode: host
    ports:
      - "5432:5432"

  ap:
    image: application
    network_mode: host
    ports:
      - "8080:8080"
    depends_on:
      - db