version: "3"
services:
  springbootapp:
    image: springbootapp:latest
    container_name: springbootapp
    ports:
      - 8080:8080
    depends_on:
      - docker-postgres
  docker-postgres:
    image: postgres:10.4
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db