version: "3"
services:
  db:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
    ports:
      - "1111:5432"
  myapp:
    build: ../Dockerfile
    image: myapp
    container_name: myapp
    ports:
        - 8080:8080
    depends_on:
      - db
